version: '3.8'

services:
  minio:
    image: quay.io/minio/minio:latest
    ports:
      - "9000:9000" # MinIO API and Console
      - "9001:9001" # MinIO Console (separate port for newer versions)
    volumes:
      - minio_data:/data # Persistent storage for MinIO data
    environment:
      MINIO_ROOT_USER: minioadmin
      MINIO_ROOT_PASSWORD: minioadmin
      MINIO_SERVER_URL: http://localhost:9000 # Accessible from host
    command: server /data --console-address ":9001"
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:9000/minio/health/live"]
      interval: 30s
      timeout: 20s
      retries: 3
      start_period: 10s # Give MinIO some time to start before first health check

  ebooklibrary:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    environment:
      # These will be configured in application.yaml or application-local.yaml
      # For now, just placeholders
      MINIO_ENDPOINT: http://minio:9000 # Accessible from within the docker-compose network
      MINIO_ACCESS_KEY: minioadmin
      MINIO_SECRET_KEY: minioadmin
    depends_on:
      minio:
        condition: service_healthy

volumes:
  minio_data:
