db:
  schema: ebooklib

spring:
  application:
    name: ebooklib
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  liquibase:
    contexts: schema,default-user
    liquibase-schema: public

app:
  security:
    enabled: true
  import:
    cleanup:
      cron: "0 0 * * * *"

management:
  endpoints:
    web:
      exposure:
        include: health
  endpoint:
    health:
      show-details: never

preliquibase:
  enabled: false

logging:
  level:
    root: INFO
    com.mikesajak.ebooklib: TRACE
    liquibase: INFO
