db:
  schema: ebooklib

spring:
  application:
    name: ebooklib
  servlet:
    multipart:
      max-file-size: 100MB
      max-request-size: 100MB
  liquibase:

app:
  security:
    enabled: false
  import:
    cleanup:
      cron: "0 0 * * * *"

preliquibase:
  enabled: false

logging:
  level:
    root: INFO
    com.mikesajak.ebooklib: TRACE
    liquibase: INFO
